(function(){'use strict';
const D=window.StockData, app=document.getElementById('cycle-app'), params=new URLSearchParams(location.search);
const cycleId=params.get('cycle')||'cycle-1', cycle=D.getCycle(cycleId);
if(!cycle){app.innerHTML='<section class="r-empty"><h1>找不到這個循環</h1><a href="../index.html#industries">返回三大循環</a></section>';return;}
let market=['tw','us'].includes(params.get('market'))?params.get('market'):'us';
let industry=D.normalizeIndustryName(params.get('industry')||''); if(!cycle.industries.includes(industry)) industry=cycle.industries[0];
let search='', sort='ticker';
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function sync(){const p=new URLSearchParams({cycle:cycle.id,market,industry});history.pushState(null,'',`?${p}`);render();}
function stockHref(s){return `stock.html?market=${s.market}&ticker=${encodeURIComponent(s.ticker)}&cycle=${cycle.id}&industry=${encodeURIComponent(industry)}`;}
function card(s){const records=s.records.filter(r=>r.industry===industry), latest=records[0]||s.records[0], labels=[...new Set(records.map(r=>r.rawBenefitLabel).filter(Boolean))];
 const extra=s.market==='tw'?`<p>${esc((latest.rationale||'資料未提供').slice(0,90))}</p><dl><div><dt>原始分類</dt><dd>${esc(labels.join('、')||'分類待查核')}</dd></div><div><dt>查核截止日</dt><dd>${esc(latest.checkedAt||'資料未提供')}</dd></div></dl>`:`<dl><div><dt>最新政策狀態</dt><dd>${esc(latest.policyStatus||'資料未提供')}</dd></div><div><dt>最新事件日期</dt><dd>${esc(latest.eventDate||'資料未提供')}</dd></div><div><dt>政策事件</dt><dd>${records.length} 筆</dd></div><div><dt>事件日至今漲幅</dt><dd class="${latest.returnValue>0?'is-up':latest.returnValue<0?'is-down':''}">${esc(latest.returnRaw||'資料未提供')}</dd></div></dl>`;
 const inner=`<div class="stock-card__top"><span class="market-pill">${s.market==='tw'?'台股':'美股'}</span><span>${s.benefitGroup==='confirmed'?'已確認受惠':s.benefitGroup==='unconfirmed'?'未確認直接受惠':'分類待查核'}</span></div><strong>${esc(s.ticker||'股票代號未提供')}</strong><h3>${esc(s.companyName)}</h3><small>${esc(industry)}</small>${extra}<span class="stock-card__more">${s.ticker?'查看個股研究 →':'不可建立個股連結'}</span>`;
 return s.ticker?`<a class="stock-card" href="${stockHref(s)}">${inner}</a>`:`<article class="stock-card is-disabled">${inner}</article>`;}
function render(){const stocks=window.__stocks||[]; const counts=Object.fromEntries(cycle.industries.map(i=>[i,stocks.filter(s=>s.market===market&&s.industries.includes(i)).length]));
 let list=stocks.filter(s=>s.market===market&&s.industries.includes(industry)&&(!search||`${s.ticker} ${s.companyName}`.toLowerCase().includes(search.toLowerCase())));
 list.sort((a,b)=>{if(sort==='company')return a.companyName.localeCompare(b.companyName,'zh-Hant');if(sort==='date'){const br=b.records.find(r=>r.industry===industry),ar=a.records.find(r=>r.industry===industry);return((br?.eventDate||br?.checkedAt)||'').localeCompare((ar?.eventDate||ar?.checkedAt)||'');}return a.ticker.localeCompare(b.ticker,undefined,{numeric:true});});
 const groups=['confirmed','unconfirmed','unclassified'];
 app.innerHTML=`<nav class="breadcrumb"><a href="../index.html">首頁</a><span>/</span><span>${cycle.title}</span></nav><section class="cycle-hero"><p>CYCLE ${cycle.number} / 03</p><h1>${cycle.title}</h1><h2>${cycle.subtitle}</h2><p>${cycle.description}</p></section>
 <nav class="market-tabs cycle-switcher" style="display:flex;margin-bottom:10px" aria-label="循環切換">${D.CYCLES.map(c=>`<button type="button" aria-selected="${c.id===cycle.id}" data-cycle="${c.id}">循環 ${String(c.number).padStart(2,'0')}｜${esc(c.title)}</button>`).join('')}</nav>
 <div class="market-tabs" role="tablist" aria-label="市場切換"><button role="tab" aria-selected="${market==='us'}" data-market="us">美股</button><button role="tab" aria-selected="${market==='tw'}" data-market="tw">台股</button></div>
 <section class="cycle-layout"><aside><h2>選擇產業</h2><div class="industry-tabs" role="tablist" aria-label="${cycle.title}產業">${cycle.industries.map(i=>`<button role="tab" aria-selected="${i===industry}" data-industry="${esc(i)}"><span>${esc(i)}</span><small>${counts[i]?`${counts[i]} 檔`:'目前無資料'}</small></button>`).join('')}</div></aside>
 <div class="stocks-panel"><header><div><p class="eyebrow">${market==='tw'?'TAIWAN':'UNITED STATES'} / ${list.length} STOCKS</p><h2>${esc(industry)}</h2></div><div class="tools"><label>搜尋<input id="stock-search" type="search" value="${esc(search)}" placeholder="代號或公司名稱"></label><label>排序<select id="stock-sort"><option value="ticker" ${sort==='ticker'?'selected':''}>股票代號</option><option value="company" ${sort==='company'?'selected':''}>公司名稱</option><option value="date" ${sort==='date'?'selected':''}>事件日期</option></select></label></div></header>
 ${groups.map(g=>{const items=list.filter(s=>s.benefitGroup===g);const title=g==='confirmed'?'已確認受惠':g==='unconfirmed'?'未確認直接受惠':'分類待查核';return `<section class="benefit-group"><h3>${title} <span>${items.length}</span></h3>${items.length?`<div class="stock-grid">${items.map(card).join('')}</div>`:'<div class="r-empty">此市場與產業目前沒有這類資料。</div>'}</section>`;}).join('')}</div></section>
 <footer class="disclaimer">資料查核日期依各筆來源檔案記載；美股漲幅截至 2026-07-17。本頁為依來源資料建立的研究分類，不構成投資建議。來源檔案未提供每日行情與技術指標。</footer>`;
 app.querySelectorAll('[data-cycle]').forEach(b=>b.onclick=()=>{const next=D.getCycle(b.dataset.cycle);location.href=`?${new URLSearchParams({cycle:next.id,market,industry:next.industries[0]})}`;}); app.querySelectorAll('[data-market]').forEach(b=>b.onclick=()=>{market=b.dataset.market;sync();}); app.querySelectorAll('[data-industry]').forEach(b=>b.onclick=()=>{industry=b.dataset.industry;sync();});
 document.getElementById('stock-search').oninput=e=>{search=e.target.value;render();document.getElementById('stock-search').focus();}; document.getElementById('stock-sort').onchange=e=>{sort=e.target.value;render();};}
window.addEventListener('popstate',()=>location.reload()); D.loadData('../').then(data=>{window.__stocks=data.stocks;render();}).catch(e=>app.innerHTML=`<div class="r-empty"><h1>資料載入失敗</h1><p>${esc(e.message)}</p></div>`);
})();
