const fs=require('fs'),vm=require('vm'),assert=require('assert'),path=require('path');
const root=path.resolve(__dirname,'..');
const context={window:{},console,fetch:async url=>({ok:true,text:async()=>fs.readFileSync(path.join(root,String(url).replace(/^\.\.\//,'')),'utf8')})};
vm.createContext(context);vm.runInContext(fs.readFileSync(path.join(root,'js/cycle-data.js'),'utf8'),context);
const D=context.window.StockData;
(async()=>{const data=await D.loadData('../');
assert.deepStrictEqual(Array.from(D.CYCLES,c=>c.industries.length),[3,7,10]);
const industries=D.CYCLES.flatMap(c=>Array.from(c.industries));assert.strictEqual(industries.length,20);assert.strictEqual(new Set(industries).size,20);
assert.strictEqual(data.twRows.length,102);assert.strictEqual(data.usRows.length,524);
assert.strictEqual(D.normalizeIndustryName('資安／聯邦IT現代化'),'資安／聯邦 IT 現代化');
assert.strictEqual(D.normalizeIndustryName('半導體／美國製造／AI晶片'),'半導體／美國製造／AI 晶片');
assert.strictEqual(D.normalizeTicker('2330.0'),'2330');assert.strictEqual(D.normalizeTicker('nan'),'');
assert.strictEqual(D.parsePercent('+12.34%'),12.34);assert.strictEqual(D.parsePercent('-12.34%'),-12.34);
assert.ok(data.records.every(r=>['confirmed','unconfirmed','unclassified'].includes(r.benefitGroup)));
assert.strictEqual(data.records.filter(r=>r.benefitGroup==='unclassified').length,0);
const keyed=data.stocks.filter(s=>s.ticker).map(s=>`${s.market}:${s.ticker}`);assert.strictEqual(keyed.length,new Set(keyed).size);
assert.ok(data.stocks.some(s=>s.market==='us'&&s.records.length>1));assert.ok(data.stocks.some(s=>s.market==='tw'&&s.industries.length>1));
assert.ok(data.stocks.filter(s=>s.market==='tw'&&!s.ticker).every(s=>!s.ticker));
console.log(JSON.stringify({cycles:D.CYCLES.map(c=>c.industries.length),industries:new Set(industries).size,twRows:data.twRows.length,usRows:data.usRows.length,stocks:data.stocks.length,multiEventUS:data.stocks.filter(s=>s.market==='us'&&s.records.length>1).length,multiIndustryTW:data.stocks.filter(s=>s.market==='tw'&&s.industries.length>1).length,missingTickerTW:data.stocks.filter(s=>s.market==='tw'&&!s.ticker).length,unclassified:data.records.filter(r=>r.benefitGroup==='unclassified').length},null,2));
})().catch(e=>{console.error(e);process.exitCode=1;});
